class AppStrings {
  final String locale;

  const AppStrings(this.locale);

  static const _ru = <String, String>{
    'appTitle': 'KHS',
    'today': 'Сегодня',
    'tasks': 'Задачи',
    'calendar': 'Календарь',
    'settings': 'Настройки',
    'quickAddHint': 'Быстрый ввод: напиши задачу, дату, время…',
    'quickAddExample': 'Например: «позвонить врачу завтра в 15:00 !важно»',
    'addTask': 'Добавить задачу',
    'editTask': 'Редактировать задачу',
    'title': 'Название',
    'titleHint': 'Что нужно сделать?',
    'notes': 'Заметки',
    'notesHint': 'Дополнительные детали…',
    'dueDate': 'Срок',
    'dueTime': 'Время',
    'noDueDate': 'Без срока',
    'recurringAutoDate': 'Автоматически (каждый день)',
    'priority': 'Приоритет',
    'low': 'Низкий',
    'normal': 'Средний',
    'high': 'Высокий',
    'recurrence': 'Повтор',
    'never': 'Никогда',
    'daily': 'Ежедневно',
    'weekly': 'Еженедельно',
    'monthly': 'Ежемесячно',
    'reminder': 'Напоминание',
    'noReminder': 'Без напоминания',
    'remindOnTime': 'В назначенное время',
    'remind5min': 'За 5 минут',
    'remind30min': 'За 30 минут',
    'remind1hour': 'За 1 час',
    'remind1day': 'За 1 день',
    'chooseTime': 'Выберите время',
    'customTime': 'Своё время…',
    'hours': 'Часы',
    'minutes': 'Минуты',
    'notifyReminder': 'Пуш-уведомление (СМС)',
    'notifyReminderSubtitle': 'Придёт уведомление в выбранное время',
    'themeColor': 'Цвет темы',
    'themeColorSubtitle': 'Акцент приложения — выбери любой цвет',
    'darkTheme': 'Тёмная тема',
    'lightTheme': 'Светлая тема',
    'appearance': 'Внешний вид',
    'updateNoAddress': 'Сначала укажи адрес ПК в настройках синхронизации',
    'updateConnectFail': 'ПК недоступен. Убедись, что KHS запущен на ПК и сервер включён в настройках.',
    'upToDateRemote': 'Установлена последняя версия',
    'historyOfflineNote': 'ПК недоступен — показываю историю из приложения. Запусти KHS на ПК, чтобы увидеть актуальную.',
    'updateRemoteTitle': 'Доступна новая версия v{1}',
    'download': 'Скачать',
    'noUpdateFile': 'Файл обновления не найден на ПК',
    'downloading': 'Скачивание с ПК…',
    'installPrompt':
        'Файл скачан. Установи обновление, следуя подсказкам Android',
    'openFileFailed': 'Не удалось открыть файл обновления',
    'savedTo': 'Файл сохранён',
    'downloadFailed': 'Не удалось скачать обновление',
    'allowInstallTitle': 'Разрешить установку обновлений',
    'allowInstallBody': 'Для установки обновлений из этого приложения включи «Установка из неизвестных источников» для KHS в настройках Android.',
    'openSettings': 'Открыть настройки',
    'save': 'Сохранить',
    'cancel': 'Отмена',
    'back': 'Назад',
    'delete': 'Удалить',
    'deleteConfirm': 'Удалить задачу?',
    'emptyTasks': 'Задач на этот день нет',
    'emptyAll': 'Нет задач. Добавь первую!',
    'completed': 'Выполнено',
    'language': 'Язык',
    'russian': 'Русский',
    'english': 'English',
    'about': 'О приложении',
    'version': 'Версия',
    'ok': 'ОК',
    'whatsNew': 'Что нового',
    'whatsNewTitle': 'Что нового в KHS',
    'changelog':
        '• Трёхпанельный дашборд: задачи, детали, напоминания\n'
        '• Заметки: заметка дня и отдельные заметки\n'
        '• Группы и теги задач (#тег)\n'
        '• Синхронизация с Obsidian\n'
        '• Напоминания и уведомления\n'
        '• Календарь и планирование',
    'noTasksScheduled': 'Нет задач с этим сроком',
    'tasksFor': 'Задачи на',
    'mon': 'Пн',
    'tue': 'Вт',
    'wed': 'Ср',
    'thu': 'Чт',
    'fri': 'Пт',
    'sat': 'Сб',
    'sun': 'Вс',
    'notificationChannel': 'Напоминания о задачах',
    'notificationChannelDesc': 'Уведомления о сроках задач',
    'overdue': 'Просрочено',
    'taskTitleRequired': 'Введите название задачи',
    'settingsSaved': 'Настройки сохранены',
    'obsidian': 'Obsidian',
    'vaultPath': 'Путь к vault',
    'vaultPathHint': 'Например: C:\\Users\\…\\Documents\\obsidean\\test',
    'vaultPathSaved': 'Путь к vault сохранён',
    'vaultQuickSwitch': 'Быстрое переключение vault',
    'chooseFolder': 'Выбрать папку',
    'vaultPicked': 'Vault выбран и подключён',
    'vaultNotPicked': 'Папка не выбрана',
    'allFilesAccessTitle': 'Доступ ко всем файлам',
    'allFilesAccessBody': 'Для работы с vault на телефоне разреши KHS доступ ко всем файлам (Настройки → Доступ ко всем файлам).',
    'grantThenPickVault':
        'Включи доступ ко всем файлам и нажми «Выбрать папку» снова',
    'saveVaultPath': 'Сохранить путь',
    'syncNow': 'Синхронизировать сейчас',
    'syncDone': 'Готово: добавлено {1}, обновлено {2}, записано {3}',
    'syncFailed': 'Синхронизация не удалась: {1}',
    'noVaultPath': 'Не указан путь к vault',
    'obsidianHelp':
        'Задачи записываются в ежедневную заметку vault (даты/YYYY/месяцы/…)',
    'groups': 'Группы',
    'newGroup': 'Новая группа',
    'createGroup': 'Создать группу',
    'groupName': 'Название группы',
    'create': 'Создать',
    'rename': 'Переименовать',
    'deleteGroupConfirm': 'Удалить группу? Задачи группы останутся без группы.',
    'allTasks': 'Все задачи',
    'all': 'Все',
    'priorityHigh': 'Высокие',
    'priorityMedium': 'Средние',
    'priorityLow': 'Низкие',
    'events': 'События',
    'progress': 'Прогресс',
    'statistics': 'Статистика',
    'dailyGoal': 'Дневная цель',
    'streak': 'Серия',
    'thisWeek': 'Неделя',
    'progressBars': 'Статистика',
    'progressBarsSubtitle': 'Что показывать на экране статистики',
    'barGroups': 'Столбики по группам',
    'barPriorities': 'Столбики по приоритетам',
    'barPeriods': 'Сегодня / неделя',
    'barGoal': 'Дневная цель и серия',
    'barOverdue': 'Сводка по просроченным',
    'barSidebar': 'Бары в сайдбаре',
    'barWeek': 'График за неделю',
    'barMonth': 'График за месяц',
    'barMonthCompare': 'Сравнение месяцев',
    'doneCount': 'Выполнено',
    'remaining': 'Осталось',
    'lastWeek': 'За 7 дней',
    'lastMonth': 'За 30 дней',
    'thisMonth': 'Этот месяц',
    'prevMonth': 'Прошлый месяц',
    'schedule': 'Расписание',
    'nextReminder': 'Ближайшее напоминание',
    'addTaskShort': 'Добавить задачу',
    'tomorrow': 'Завтра',
    'noGroup': 'Без группы',
    'timer': 'Таймер',
    'chat': 'Чат',
    'geo': 'Геолокация',
    'reminders': 'Напоминания',
    'upcomingReminders': 'Запланированные напоминания',
    'noReminders': 'Нет запланированных напоминаний',
    'addTag': 'Добавить тег',
    'design': 'Заметки',
    'home': 'Главная',
    'noNotes': 'Нет заметок. Создай первую!',
    'createNote': 'Новая заметка',
    'editNote': 'Редактировать заметку',
    'noteTitleHint': 'Заголовок…',
    'noteContentHint': 'Текст заметки…',
    'noteTitleRequired': 'Введите заголовок заметки',
    'deleteNoteConfirm': 'Удалить заметку?',
    'tagAdded': 'Тег добавлен',
    'selectTaskFirst': 'Сначала выбери задачу (нажми на неё)',
    'notifications': 'Уведомления',
    'notificationsEnabled': 'Включить уведомления',
    'backgroundWork': 'Работа в фоне',
    'backgroundWorkOk':
        'Оптимизация батареи для KHS не ограничена — напоминания приходят',
    'backgroundWorkWarn': 'Нажмите, чтобы разрешить KHS работу в фоне (важно, если пуши не приходят)',
    'exactAlarm': 'Точный будильник',
    'exactAlarmOk':
        'Точные будильники разрешены — напоминания приходят вовремя',
    'exactAlarmWarn': 'Нажмите, чтобы разрешить точные будильники',
    'testNotification': 'Проверить уведомление',
    'testNotificationHelp': 'Пробное уведомление через 10 секунд',
    'testNotificationSent': 'Тестовое уведомление отправлено',
    'testNotificationTitle': 'KHS работает',
    'testNotificationBody': 'Уведомления доставляются',
    'notificationsHelp': 'Напоминания о задачах даже когда приложение закрыто',
    'dailyNote': 'Заметка дня',
    'standaloneNote': 'Отдельная заметка',
    'noteDate': 'Дата',
    'chooseDate': 'Выбрать дату',
    'checkUpdates': 'Проверить обновления',
    'site': 'Сайт KHS',
    'siteSubtitle': 'Промо-страница приложения',
    'siteConfirm': 'Точно открыть сайт KHS в браузере?',
    'siteOpen': 'Открыть',
    'updateAvailable': 'Доступно обновление',
    'upToDate': 'У тебя последняя версия',
    'currentVersion': 'Текущая версия',
    'howToGetUpdate': 'Скачай новую версию на ПК: папка KHS-Windows и файл KHS.apk на рабочем столе.',
    'whatsNewIn': 'Что нового в этой версии',
    'versionHistory': 'История версий',
    'makeNewNote': 'Сделать новую заметку',
    'developer': 'Разработчик',
    'syncTitle': 'Синхронизация с ПК',
    'syncPhoneHelp': 'Телефон работает сам по себе. Когда он рядом с ПК в одной Wi-Fi-сети, данные передаются автоматически.',
    'syncAddress': 'Адрес ПК',
    'syncAddressHint': 'IP:порт — адрес показан в настройках ПК',
    'syncToken': 'Ключ доступа (необязательно)',
    'syncTokenHint': 'Если ключ задан на ПК, введи его здесь',
    'checkConnection': 'Проверить подключение',
    'connectionOk': 'Подключение есть',
    'connectionFail': 'ПК не найден',
    'lastSync': 'Последняя синхронизация',
    'neverSynced': 'не было',
    'syncStatusOk': 'успешно',
    'syncStatusOffline': 'ПК недоступен',
    'syncStatusError': 'ошибка',
    'syncBusy': 'Синхронизация…',
    'pcAccess': 'Доступ с телефона',
    'pcAccessHelp': 'Включи, чтобы телефон мог пользоваться хранилищем ПК по Wi-Fi. ПК и телефон должны быть в одной сети. Если телефон не видит ПК — открой порт в брандмауэре Windows.',
    'syncPort': 'Порт',
    'pcAddresses': 'Адреса ПК',
    'newNoteArrived': 'Новая заметка',
    'noteReminder': 'Напоминание про заметку дня',
    'noteReminderHelp': 'Ежедневное напоминание написать заметку дня',
    'noteReminderBody': 'Пора написать заметку дня',
    'syncSettingsSaved': 'Настройки синхронизации сохранены',
    'done': 'Выполнена',
    'trash': 'Корзина',
    'trashEmpty': 'Корзина пуста',
    'restore': 'Восстановить',
    'deleteForever': 'Удалить навсегда',
    'deleteForeverConfirm':
        'Удалить заметку навсегда? Это действие необратимо.',
    'defaultNoteTitle': 'Без названия',
    'connectionFailHelpTitle': 'ПК не найден',
    'connectionFailHelpBody':
        'Проверь:\n'
        '1. ПК и телефон подключены к одной Wi-Fi-сети.\n'
        '2. На ПК в настройках включён «Доступ с телефона».\n'
        '3. Адрес введён как показано в настройках ПК.\n'
        '4. В брандмауэре Windows разрешён доступ для KHS '
        '(на ПК: «Открыть порт в брандмауэре»).',
    'checkServer': 'Проверить сервер',
    'serverOk': 'Сервер работает',
    'serverFail': 'Сервер не отвечает',
    'firewallOpen': 'Открыть порт в брандмауэре',
    'firewallOpened': 'Порт открыт в брандмауэре',
    'firewallFailed': 'Не удалось открыть порт автоматически — запусти KHS от имени администратора или добавь правило вручную',
    'firewallPcOnly': 'Доступно только на ПК',
    'showAddresses': 'Показать адреса',
    'hideAddresses': 'Скрыть адреса',
    'pcAddressesNote': 'Это адрес только этого ПК в твоей локальной сети — у каждого пользователя свой.',
  };

  static const _en = <String, String>{
    'appTitle': 'KHS',
    'today': 'Today',
    'tasks': 'Tasks',
    'calendar': 'Calendar',
    'settings': 'Settings',
    'quickAddHint': 'Quick add: type a task, date, time…',
    'quickAddExample': 'e.g. "call the doctor tomorrow at 15:00 !high"',
    'addTask': 'Add task',
    'editTask': 'Edit task',
    'title': 'Title',
    'titleHint': 'What needs to be done?',
    'notes': 'Notes',
    'notesHint': 'Additional details…',
    'dueDate': 'Due date',
    'dueTime': 'Time',
    'noDueDate': 'No due date',
    'recurringAutoDate': 'Auto (every day)',
    'priority': 'Priority',
    'low': 'Low',
    'normal': 'Medium',
    'high': 'High',
    'recurrence': 'Recurrence',
    'never': 'Never',
    'daily': 'Daily',
    'weekly': 'Weekly',
    'monthly': 'Monthly',
    'reminder': 'Reminder',
    'noReminder': 'No reminder',
    'remindOnTime': 'At due time',
    'remind5min': '5 minutes before',
    'remind30min': '30 minutes before',
    'remind1hour': '1 hour before',
    'remind1day': '1 day before',
    'chooseTime': 'Select time',
    'customTime': 'Custom time…',
    'hours': 'Hours',
    'minutes': 'Minutes',
    'notifyReminder': 'Push notification (SMS)',
    'notifyReminderSubtitle': 'Get a notification at the chosen time',
    'themeColor': 'Theme color',
    'themeColorSubtitle': 'App accent — pick any color',
    'darkTheme': 'Dark theme',
    'lightTheme': 'Light theme',
    'appearance': 'Appearance',
    'updateNoAddress': 'Set the PC address in sync settings first',
    'updateConnectFail': 'PC unavailable. Make sure KHS is running on PC and the server is enabled in settings.',
    'upToDateRemote': 'You have the latest version',
    'historyOfflineNote': 'PC is unavailable — showing the built-in history. Start KHS on your PC to see the latest.',
    'updateRemoteTitle': 'New version v{1} available',
    'download': 'Download',
    'noUpdateFile': 'No update file on the PC',
    'downloading': 'Downloading from PC…',
    'installPrompt':
        'File downloaded. Install the update following Android prompts',
    'openFileFailed': 'Could not open the update file',
    'savedTo': 'File saved',
    'downloadFailed': 'Could not download the update',
    'allowInstallTitle': 'Allow installing updates',
    'allowInstallBody': 'To install updates from this app, enable “Install unknown apps” for KHS in Android settings.',
    'openSettings': 'Open settings',
    'save': 'Save',
    'cancel': 'Cancel',
    'back': 'Back',
    'delete': 'Delete',
    'deleteConfirm': 'Delete task?',
    'emptyTasks': 'No tasks for this day',
    'emptyAll': 'No tasks yet. Add your first one!',
    'completed': 'Completed',
    'language': 'Language',
    'russian': 'Русский',
    'english': 'English',
    'about': 'About',
    'version': 'Version',
    'ok': 'OK',
    'whatsNew': "What's new",
    'whatsNewTitle': "What's new in KHS",
    'changelog':
        '• Three-panel dashboard: tasks, details, reminders\n'
        '• Notes: daily note and standalone notes\n'
        '• Task groups and tags (#tag)\n'
        '• Obsidian sync\n'
        '• Reminders and notifications\n'
        '• Calendar and planning',
    'noTasksScheduled': 'No tasks with this due date',
    'tasksFor': 'Tasks for',
    'mon': 'Mo',
    'tue': 'Tu',
    'wed': 'We',
    'thu': 'Th',
    'fri': 'Fr',
    'sat': 'Sa',
    'sun': 'Su',
    'notificationChannel': 'Task reminders',
    'notificationChannelDesc': 'Notifications about task due dates',
    'overdue': 'Overdue',
    'taskTitleRequired': 'Enter a task title',
    'settingsSaved': 'Settings saved',
    'obsidian': 'Obsidian',
    'vaultPath': 'Vault path',
    'vaultPathHint': 'e.g. C:\\Users\\…\\Documents\\obsidean\\test',
    'vaultPathSaved': 'Vault path saved',
    'vaultQuickSwitch': 'Quick vault switch',
    'chooseFolder': 'Choose folder',
    'vaultPicked': 'Vault selected and connected',
    'vaultNotPicked': 'No folder selected',
    'allFilesAccessTitle': 'Access all files',
    'allFilesAccessBody': 'To use a vault on the phone, allow KHS to access all files (Settings → All files access).',
    'grantThenPickVault':
        'Enable all-files access, then press “Choose folder” again',
    'saveVaultPath': 'Save path',
    'syncNow': 'Sync now',
    'syncDone': 'Done: {1} added, {2} updated, {3} written',
    'syncFailed': 'Sync failed: {1}',
    'noVaultPath': 'No vault path set',
    'obsidianHelp':
        'Tasks are written to the vault daily note (dates/YYYY/months/…)',
    'groups': 'Groups',
    'newGroup': 'New group',
    'createGroup': 'Create group',
    'groupName': 'Group name',
    'create': 'Create',
    'rename': 'Rename',
    'deleteGroupConfirm': 'Delete group? Its tasks stay without a group.',
    'allTasks': 'All tasks',
    'all': 'All',
    'priorityHigh': 'High',
    'priorityMedium': 'Medium',
    'priorityLow': 'Low',
    'events': 'Events',
    'progress': 'Progress',
    'statistics': 'Statistics',
    'dailyGoal': 'Daily goal',
    'streak': 'Streak',
    'thisWeek': 'Week',
    'progressBars': 'Statistics',
    'progressBarsSubtitle': 'What to show on the statistics screen',
    'barGroups': 'Group bars',
    'barPriorities': 'Priority bars',
    'barPeriods': 'Today / week',
    'barGoal': 'Daily goal & streak',
    'barOverdue': 'Overdue summary',
    'barSidebar': 'Sidebar bars',
    'barWeek': 'Week chart',
    'barMonth': 'Month chart',
    'barMonthCompare': 'Month comparison',
    'doneCount': 'Done',
    'remaining': 'Remaining',
    'lastWeek': 'Last 7 days',
    'lastMonth': 'Last 30 days',
    'thisMonth': 'This month',
    'prevMonth': 'Last month',
    'schedule': 'Schedule',
    'nextReminder': 'Upcoming reminder',
    'addTaskShort': 'Add task',
    'tomorrow': 'Tomorrow',
    'noGroup': 'No group',
    'timer': 'Timer',
    'chat': 'Chat',
    'geo': 'Geolocation',
    'reminders': 'Reminders',
    'upcomingReminders': 'Scheduled reminders',
    'noReminders': 'No scheduled reminders',
    'addTag': 'Add tag',
    'design': 'Notes',
    'home': 'Home',
    'noNotes': 'No notes yet. Create one!',
    'createNote': 'New note',
    'editNote': 'Edit note',
    'noteTitleHint': 'Title…',
    'noteContentHint': 'Note text…',
    'noteTitleRequired': 'Enter a note title',
    'deleteNoteConfirm': 'Delete note?',
    'tagAdded': 'Tag added',
    'selectTaskFirst': 'Select a task first (tap one)',
    'notifications': 'Notifications',
    'notificationsEnabled': 'Enable notifications',
    'backgroundWork': 'Background work',
    'backgroundWorkOk':
        'Battery optimization is not restricted — reminders arrive',
    'backgroundWorkWarn': 'Tap to allow KHS to run in background (important if pushes do not arrive)',
    'exactAlarm': 'Exact alarm',
    'exactAlarmOk': 'Exact alarms allowed — reminders arrive on time',
    'exactAlarmWarn': 'Tap to allow exact alarms',
    'testNotification': 'Test notification',
    'testNotificationHelp': 'A test notification in 10 seconds',
    'testNotificationSent': 'Test notification sent',
    'testNotificationTitle': 'KHS is working',
    'testNotificationBody': 'Notifications are delivered',
    'notificationsHelp': 'Task reminders even when the app is closed',
    'dailyNote': 'Daily note',
    'standaloneNote': 'Standalone note',
    'noteDate': 'Date',
    'chooseDate': 'Choose date',
    'checkUpdates': 'Check for updates',
    'site': 'KHS site',
    'siteSubtitle': 'App promo page',
    'siteConfirm': 'Open the KHS website in the browser?',
    'siteOpen': 'Open',
    'updateAvailable': 'Update available',
    'upToDate': "You're up to date",
    'currentVersion': 'Current version',
    'howToGetUpdate': 'Download the new version on your PC: the KHS-Windows folder and KHS.apk on the desktop.',
    'whatsNewIn': "What's new in this version",
    'versionHistory': 'Version history',
    'makeNewNote': 'Make a new note',
    'developer': 'Developer',
    'syncTitle': 'PC sync',
    'syncPhoneHelp': 'The phone works on its own. When it is near the PC on the same Wi-Fi, data transfers automatically.',
    'syncAddress': 'PC address',
    'syncAddressHint': 'IP:port — shown in PC settings',
    'syncToken': 'Access key (optional)',
    'syncTokenHint': 'If a key is set on the PC, enter it here',
    'checkConnection': 'Check connection',
    'connectionOk': 'Connected',
    'connectionFail': 'PC not found',
    'lastSync': 'Last sync',
    'neverSynced': 'never',
    'syncStatusOk': 'ok',
    'syncStatusOffline': 'PC unreachable',
    'syncStatusError': 'error',
    'syncBusy': 'Syncing…',
    'pcAccess': 'Phone access',
    'pcAccessHelp': 'Enable so the phone can use the PC storage over Wi-Fi. PC and phone must be on the same network. If the phone cannot find the PC, open the port in Windows Firewall.',
    'syncPort': 'Port',
    'pcAddresses': 'PC addresses',
    'newNoteArrived': 'New note',
    'noteReminder': 'Daily note reminder',
    'noteReminderHelp': 'A daily reminder to write the daily note',
    'noteReminderBody': "It's time to write the daily note",
    'syncSettingsSaved': 'Sync settings saved',
    'done': 'Done',
    'trash': 'Trash',
    'trashEmpty': 'Trash is empty',
    'restore': 'Restore',
    'deleteForever': 'Delete forever',
    'deleteForeverConfirm': 'Delete this note forever? This cannot be undone.',
    'defaultNoteTitle': 'Untitled',
    'connectionFailHelpTitle': 'PC not found',
    'connectionFailHelpBody':
        'Check that:\n'
        '1. PC and phone are on the same Wi-Fi.\n'
        '2. "Phone access" is enabled in PC settings.\n'
        '3. The address matches the one shown in PC settings.\n'
        '4. Windows Firewall allows KHS '
        '(on the PC tap "Open port in firewall").',
    'checkServer': 'Check server',
    'serverOk': 'Server is running',
    'serverFail': 'Server is not responding',
    'firewallOpen': 'Open port in firewall',
    'firewallOpened': 'Port opened in firewall',
    'firewallFailed': 'Could not open the port automatically — run KHS as administrator or add the rule manually',
    'firewallPcOnly': 'Only available on PC',
    'showAddresses': 'Show addresses',
    'hideAddresses': 'Hide addresses',
    'pcAddressesNote': 'This is only this PC address in your local network — each user has their own.',
  };

  String get _table => locale.startsWith('ru') ? 'ru' : 'en';

  Map<String, String> get _strings => _table == 'ru' ? _ru : _en;

  String t(String key) => _strings[key] ?? key;

  bool get isRussian => _table == 'ru';
}
